@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jun 02 09:18:08 +0300 2022
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Project2Sim_behav -key {Behavioral:sim_1:Functional:Project2Sim} -tclbatch Project2Sim.tcl -view C:/Users/sowxl/Desktop/project_2/Project2Sim.wcfg -log simulate.log"
call xsim  Project2Sim_behav -key {Behavioral:sim_1:Functional:Project2Sim} -tclbatch Project2Sim.tcl -view C:/Users/sowxl/Desktop/project_2/Project2Sim.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
